import React,{useEffect,useState} from 'react';
import {getStoredUser} from '../services/auth';
import {getMyArtworks,getApiUrl,uploadArtwork,analyzeArtwork,mintArtwork} from '../services/api';
const tabs=['Upload Artwork','Marketplace','Edit Profile'];
function Dashboard({onLogout}){
 const [active,setActive]=useState('Upload Artwork'),[user]=useState(getStoredUser()),[artworks,setArtworks]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState('');
 const [form,setForm]=useState({title:'',description:'',artwork:null});
 useEffect(()=>{getMyArtworks().then(d=>setArtworks(d.artworks||[])).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 const run=async(id,fn,success)=>{setBusy(id);setError('');try{const d=await fn(id);setArtworks(xs=>xs.map(x=>x.id===id?d.artwork:x));setMessage(success)}catch(e){setError(e.message)}finally{setBusy('')}};
 const submit=async e=>{e.preventDefault();setError('');setMessage('');if(!form.artwork)return setError('Choose an artwork image first.');setBusy('upload');try{const fd=new FormData();fd.append('title',form.title);fd.append('description',form.description);fd.append('artwork',form.artwork);const d=await uploadArtwork(fd);setArtworks(xs=>[d.artwork,...xs]);setForm({title:'',description:'',artwork:null});e.target.reset();setMessage('Artwork uploaded. Run the AI originality check next.')}catch(x){setError(x.message)}finally{setBusy('')}};
 return <main className="dashboard"><div className="dashboard-nav"><strong>AuthArt</strong><span>{user?.address?.slice(0,6)}...{user?.address?.slice(-4)}</span><button onClick={onLogout}>LOGOUT</button></div><section className="dashboard-head"><div><span className="eyebrow">AUTHART DASHBOARD</span><h1>Your creative vault.</h1><p>Identity, AI originality, minting and marketplace in one flow.</p></div><div className="identity"><span>DID</span><strong>{user?.did}</strong></div></section><div className="dashboard-tabs">{tabs.map(t=><button key={t} className={active===t?'active':''} onClick={()=>{setActive(t);setMessage('');setError('')}}>{t}</button>)}</div>{message&&<div className="notice success">{message}</div>}{error&&<div className="notice error">{error}</div>}
 {active==='Upload Artwork'&&<><section className="dashboard-grid"><form className="panel upload-panel" onSubmit={submit}><div className="panel-title"><span>01</span><div><h2>Upload artwork</h2><p>Upload an original image for the AI engine.</p></div></div><label>Title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="dropzone"><input required type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e=>setForm({...form,artwork:e.target.files?.[0]||null})}/><span>Drop image here or <b>browse</b></span><small>PNG, JPG, WEBP or GIF · max 10 MB</small></label><button className="primary-btn" disabled={busy==='upload'}>{busy==='upload'?'UPLOADING...':'UPLOAD FOR AI CHECK'}</button></form><section className="panel pipeline-panel"><div className="panel-title"><span>02</span><div><h2>End-to-end pipeline</h2><p>Each stage unlocks the next one.</p></div></div><div className="pipeline"><div className="pipeline-step current"><b>Upload</b><small>Phase 2</small></div><div className="pipeline-line"/><div className="pipeline-step"><b>AI originality</b><small>Phase 3</small></div><div className="pipeline-line"/><div className="pipeline-step"><b>Mint + royalty</b><small>Phase 4</small></div><div className="pipeline-line"/><div className="pipeline-step"><b>Marketplace</b><small>Phase 5</small></div></div></section></section><section className="panel collection"><div className="collection-head"><div><h2>My artwork</h2><p>{artworks.length} uploaded piece{artworks.length===1?'':'s'}</p></div></div>{loading?<p>Loading...</p>:artworks.length===0?<div className="empty">No artwork yet.</div>:<div className="art-grid">{artworks.map(x=><article className="art-card" key={x.id}><img src={`${getApiUrl().replace('/api','')}/uploads/${x.filename}`} alt={x.title}/><div><h3>{x.title}</h3><span>{x.aiStatus==='pending'?'AI CHECK PENDING':x.aiStatus.toUpperCase()}</span>{x.aiResult&&<small>Originality {Math.round(x.aiResult.originalityScore*100)}% · Suggested {x.aiResult.pricePrediction?.suggestedEth||'-'} ETH</small>}<div className="card-actions">{x.aiStatus==='pending'&&<button onClick={()=>run(x.id,analyzeArtwork,'AI analysis completed.')}>{busy===x.id?'SCANNING...':'RUN AI CHECK'}</button>}{x.aiStatus==='passed'&&x.status!=='minted'&&<button onClick={()=>run(x.id,mintArtwork,'NFT minted successfully.')}>{busy===x.id?'MINTING...':'START MINTING'}</button>}{x.status==='minted'&&<b className="minted">MINTED · #{x.mint?.tokenId}</b>}</div></div></article>)}</div>}</section></>}
 {active==='Marketplace'&&<section className="panel placeholder"><span className="big-number">05</span><h2>Marketplace</h2><p>Your marketplace is connected to the NFT lifecycle. Listing, purchase, royalty settlement and reputation are represented by the smart-contract layer in <code>smart-contracts/</code>.</p><div className="pipeline"><div className="pipeline-step current"><b>List</b><small>Seller</small></div><div className="pipeline-line"/><div className="pipeline-step"><b>Buy</b><small>Buyer</small></div><div className="pipeline-line"/><div className="pipeline-step"><b>Royalty</b><small>EIP-2981</small></div><div className="pipeline-line"/><div className="pipeline-step"><b>Reputation</b><small>Both parties</small></div></div></section>}
 {active==='Edit Profile'&&<section className="panel profile-form"><span className="big-number">03</span><h2>Edit profile</h2><label>Wallet address<input readOnly value={user?.address||''}/></label><label>DID<input readOnly value={user?.did||''}/></label><label>Display name<input placeholder="Creator name"/></label><label>Bio<textarea placeholder="Tell collectors about yourself"/></label><button className="primary-btn" onClick={()=>setMessage('Profile form saved for the next persistence layer.')}>SAVE PROFILE</button></section>}
 </main>}
export default Dashboard;
